import type { ValidationEngine, ValidationIssue, NormalizedDocument } from '../../shared/types/domain.types';
import { generateId } from '../../shared/utils/id';

// Common English words - comprehensive list
const COMMON_WORDS = new Set([
  // Basic words
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'it', 'for', 'not', 'on', 'with',
  'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her',
  'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up',
  'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time',
  'no', 'just', 'him', 'know', 'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
  'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think',
  'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even',
  'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us', 'is', 'was', 'are', 'were',
  'been', 'has', 'had', 'did', 'does', 'doing', 'done', 'being', 'am', 'having',
  
  // Essential missing words
  'every', 'each', 'many', 'much', 'more', 'most', 'some', 'such', 'only', 'own', 'same', 'so',
  'than', 'too', 'very', 'just', 'still', 'yet', 'already', 'always', 'never', 'sometimes',
  'here', 'there', 'where', 'why', 'how', 'what', 'when', 'who', 'which', 'whose', 'whom',
  'content', 'contents', 'contend', 'contends', 'context', 'contexts',
  'website', 'websites', 'web', 'site', 'sites', 'page', 'pages', 'home', 'internet',
  'learning', 'learn', 'learns', 'learned', 'learnt', 'learns', 'study', 'studies', 'education',
  'foundation', 'foundations', 'foundational', 'basic', 'basics', 'fundamental', 'fundamentals',
  'language', 'languages', 'backbone', 'backbones', 'structure', 'structures', 'structural',
  'defining', 'define', 'defines', 'defined', 'definition', 'definitions',
  'presentation', 'presentations', 'present', 'presents', 'presenting', 'presented',
  'greg', 'hooper', 'gregory', 'author', 'authors', 'writer', 'writers', 'published', 'publish',
  'publishing', 'publisher', 'publishers', 'publication', 'publications',
  
  // Common verbs
  'write', 'writes', 'writing', 'wrote', 'written',
  'read', 'reads', 'reading',
  'create', 'creates', 'creating', 'created', 'creation',
  'develop', 'develops', 'developing', 'developed', 'development',
  'build', 'builds', 'building', 'built',
  'make', 'makes', 'making', 'made',
  'design', 'designs', 'designing', 'designed',
  'code', 'codes', 'coding', 'coded',
  'program', 'programs', 'programming', 'programmed',
  'use', 'uses', 'using', 'used', 'usage',
  'add', 'adds', 'adding', 'added', 'addition',
  'set', 'sets', 'setting',
  'need', 'needs', 'needing', 'needed',
  'help', 'helps', 'helping', 'helped',
  'try', 'tries', 'trying', 'tried',
  'keep', 'keeps', 'keeping', 'kept',
  'put', 'puts', 'putting',
  'mean', 'means', 'meaning', 'meant',
  'leave', 'leaves', 'leaving', 'left',
  'feel', 'feels', 'feeling', 'felt',
  'seem', 'seems', 'seeming', 'seemed',
  'ask', 'asks', 'asking', 'asked',
  'show', 'shows', 'showing', 'showed', 'shown',
  'hear', 'hears', 'hearing', 'heard',
  'play', 'plays', 'playing', 'played',
  'run', 'runs', 'running', 'ran',
  'move', 'moves', 'moving', 'moved',
  'live', 'lives', 'living', 'lived',
  'believe', 'believes', 'believing', 'believed',
  'bring', 'brings', 'bringing', 'brought',
  'happen', 'happens', 'happening', 'happened',
  'stand', 'stands', 'standing', 'stood',
  'lose', 'loses', 'losing', 'lost',
  'pay', 'pays', 'paying', 'paid',
  'meet', 'meets', 'meeting', 'met',
  'include', 'includes', 'including', 'included',
  'continue', 'continues', 'continuing', 'continued',
  'remain', 'remains', 'remaining', 'remained',
  
  // Common adjectives
  'big', 'small', 'large', 'little', 'long', 'short', 'high', 'low', 'new', 'old', 'young',
  'early', 'late', 'right', 'left', 'wrong', 'correct', 'true', 'false', 'real', 'actual',
  'local', 'global', 'national', 'international', 'public', 'private', 'personal',
  'general', 'specific', 'particular', 'special', 'certain', 'sure', 'clear', 'obvious',
  'possible', 'impossible', 'available', 'different', 'similar', 'same', 'various',
  'important', 'necessary', 'essential', 'required', 'needed', 'useful', 'helpful',
  'easy', 'simple', 'hard', 'difficult', 'complex', 'complicated',
  'full', 'empty', 'complete', 'whole', 'partial', 'total',
  'best', 'better', 'good', 'great', 'bad', 'worse', 'worst',
  'happy', 'sad', 'angry', 'afraid', 'sorry', 'glad', 'pleased',
  'beautiful', 'ugly', 'pretty', 'nice', 'fine', 'lovely',
  'strong', 'weak', 'powerful', 'heavy', 'light',
  'hot', 'cold', 'warm', 'cool',
  'dry', 'wet', 'clean', 'dirty',
  'rich', 'poor', 'expensive', 'cheap', 'free',
  'fast', 'quick', 'slow', 'rapid', 'immediate',
  'early', 'late', 'soon', 'recent', 'modern', 'current',
  'main', 'major', 'minor', 'key', 'primary', 'secondary',
  'able', 'unable', 'likely', 'unlikely', 'probable', 'possible',
  'common', 'normal', 'regular', 'usual', 'standard', 'typical',
  'popular', 'famous', 'known', 'unknown', 'familiar', 'strange',
  'certain', 'sure', 'uncertain', 'unsure', 'doubtful',
  'open', 'closed', 'close', 'opening', 'closing',
  'single', 'double', 'triple', 'multiple',
  'ready', 'prepared', 'available', 'unavailable',
  'original', 'copy', 'copied', 'duplicated',
  'following', 'previous', 'next', 'last', 'final',
  
  // Greetings and social
  'hello', 'world', 'welcome', 'thank', 'thanks', 'please', 'sorry', 'yes', 'no', 'okay', 'ok', 'hi', 'hey',
  'bye', 'goodbye', 'see', 'soon', 'later', 'morning', 'afternoon', 'evening', 'night',
  
  // Business/Tech
  'document', 'analysis', 'report', 'data', 'information', 'system', 'platform', 'application',
  'software', 'hardware', 'network', 'internet', 'computer', 'technology', 'digital', 'online',
  'business', 'company', 'organization', 'enterprise', 'customer', 'client', 'user', 'team',
  'management', 'project', 'service', 'product', 'solution', 'process', 'strategy', 'plan',
  'meeting', 'email', 'phone', 'address', 'contact', 'support', 'help', 'guide', 'manual',
  'file', 'folder', 'directory', 'storage', 'backup', 'security', 'password', 'login',
  'account', 'profile', 'settings', 'configuration', 'option', 'feature', 'function',
  'module', 'component', 'interface', 'design', 'development', 'testing', 'deployment',
  'production', 'environment', 'server', 'database', 'api', 'integration', 'automation',
  'analytics', 'metrics', 'performance', 'optimization', 'improvement', 'enhancement',
  'error', 'issue', 'problem', 'bug', 'fix', 'solution', 'resolution', 'troubleshooting',
  'maintenance', 'upgrade', 'update', 'version', 'release', 'changelog', 'documentation',
  'code', 'source', 'repository', 'branch', 'commit', 'merge', 'pull', 'push',
  'install', 'installation', 'setup', 'configure', 'configuration', 'deploy',
  'frontend', 'backend', 'fullstack', 'client', 'server', 'cloud', 'hosting',
  'responsive', 'mobile', 'desktop', 'browser', 'app', 'application',
  'framework', 'library', 'tool', 'tools', 'utility', 'plugin', 'extension',
  'search', 'find', 'filter', 'sort', 'order', 'group', 'category', 'tag',
  'input', 'output', 'value', 'values', 'field', 'fields', 'form', 'forms',
  'button', 'link', 'links', 'menu', 'nav', 'navigation', 'header', 'footer',
  'sidebar', 'panel', 'section', 'article', 'content', 'text', 'image', 'images',
  'video', 'audio', 'media', 'file', 'files', 'upload', 'download', 'import', 'export',
  'save', 'delete', 'remove', 'edit', 'update', 'modify', 'change', 'changes',
  'view', 'views', 'preview', 'display', 'show', 'hide', 'visible', 'hidden',
  'enable', 'disable', 'enabled', 'disabled', 'active', 'inactive',
  'success', 'successful', 'failed', 'failure', 'pending', 'processing', 'completed',
  'valid', 'invalid', 'validation', 'required', 'optional', 'mandatory',
  'permission', 'permissions', 'access', 'accessible', 'restricted', 'private', 'public',
  'share', 'sharing', 'shared', 'collaborate', 'collaboration', 'team', 'group',
  'notify', 'notification', 'notifications', 'alert', 'alerts', 'warning', 'warnings',
  'message', 'messages', 'comment', 'comments', 'feedback', 'review', 'reviews',
  'rate', 'rating', 'ratings', 'score', 'scores', 'rank', 'ranking', 'level',
  'subscribe', 'subscription', 'unsubscribe', 'follow', 'following', 'follower', 'followers',
  'connect', 'connection', 'connections', 'friend', 'friends', 'network', 'networking',
  'profile', 'profiles', 'avatar', 'picture', 'photo', 'photos', 'gallery',
  'setting', 'settings', 'preference', 'preferences', 'option', 'options', 'customize',
  'theme', 'themes', 'style', 'styles', 'layout', 'layouts', 'template', 'templates',
  'color', 'colors', 'font', 'fonts', 'size', 'sizes', 'width', 'height',
  'align', 'alignment', 'position', 'positions', 'margin', 'padding', 'border', 'borders',
  'background', 'foreground', 'opacity', 'transparent', 'transparency',
  'grid', 'flex', 'block', 'inline', 'table', 'list', 'lists', 'item', 'items',
  'container', 'containers', 'wrapper', 'wrappers', 'component', 'components',
  'element', 'elements', 'node', 'nodes', 'object', 'objects', 'class', 'classes',
  'id', 'name', 'names', 'title', 'titles', 'description', 'descriptions', 'summary',
  'label', 'labels', 'tag', 'tags', 'keyword', 'keywords', 'meta', 'property', 'properties',
  'attribute', 'attributes', 'parameter', 'parameters', 'argument', 'arguments',
  'variable', 'variables', 'constant', 'constants', 'function', 'functions', 'method', 'methods',
  'class', 'classes', 'object', 'objects', 'array', 'arrays', 'string', 'strings',
  'number', 'numbers', 'integer', 'integers', 'float', 'floats', 'boolean', 'booleans',
  'true', 'false', 'null', 'undefined', 'NaN', 'infinity',
  'return', 'returns', 'yield', 'yields', 'await', 'async', 'sync', 'promise', 'promises',
  'callback', 'callbacks', 'handler', 'handlers', 'listener', 'listeners', 'event', 'events',
  'trigger', 'triggers', 'triggered', 'dispatch', 'dispatches', 'dispatched',
  'state', 'states', 'status', 'store', 'stores', 'cache', 'caches', 'cached',
  'load', 'loads', 'loading', 'loaded', 'reload', 'reloading', 'reloaded',
  'fetch', 'fetches', 'fetching', 'fetched', 'request', 'requests', 'requested',
  'response', 'responses', 'respond', 'responds', 'responding', 'responded',
  'send', 'sends', 'sending', 'sent', 'receive', 'receives', 'receiving', 'received',
  'post', 'posts', 'posting', 'posted', 'get', 'gets', 'getting', 'got', 'gotten',
  'put', 'puts', 'putting', 'delete', 'deletes', 'deleting', 'deleted',
  'update', 'updates', 'updating', 'updated', 'create', 'creates', 'creating', 'created',
  'insert', 'inserts', 'inserting', 'inserted', 'select', 'selects', 'selecting', 'selected',
  'query', 'queries', 'queried', 'search', 'searches', 'searching', 'searched',
  'filter', 'filters', 'filtering', 'filtered', 'sort', 'sorts', 'sorting', 'sorted',
  'parse', 'parses', 'parsing', 'parsed', 'serialize', 'serializes', 'serializing', 'serialized',
  'encode', 'encodes', 'encoding', 'encoded', 'decode', 'decodes', 'decoding', 'decoded',
  'encrypt', 'encrypts', 'encrypting', 'encrypted', 'decrypt', 'decrypts', 'decrypting', 'decrypted',
  'compress', 'compresses', 'compressing', 'compressed', 'decompress', 'decompresses',
  'upload', 'uploads', 'uploading', 'uploaded', 'download', 'downloads', 'downloading', 'downloaded',
  'import', 'imports', 'importing', 'imported', 'export', 'exports', 'exporting', 'exported',
  'convert', 'converts', 'converting', 'converted', 'transform', 'transforms', 'transforming', 'transformed',
  'generate', 'generates', 'generating', 'generated', 'render', 'renders', 'rendering', 'rendered',
  'display', 'displays', 'displaying', 'displayed', 'show', 'shows', 'showing', 'showed', 'shown',
  'hide', 'hides', 'hiding', 'hid', 'hidden', 'visible', 'invisible', 'visibility',
  'enable', 'enables', 'enabling', 'enabled', 'disable', 'disables', 'disabling', 'disabled',
  'activate', 'activates', 'activating', 'activated', 'deactivate', 'deactivates', 'deactivating', 'deactivated',
  'start', 'starts', 'starting', 'started', 'stop', 'stops', 'stopping', 'stopped',
  'begin', 'begins', 'beginning', 'began', 'begun', 'end', 'ends', 'ending', 'ended',
  'finish', 'finishes', 'finishing', 'finished', 'complete', 'completes', 'completing', 'completed',
  'cancel', 'cancels', 'canceling', 'cancelled', 'abort', 'aborts', 'aborting', 'aborted',
  'pause', 'pauses', 'pausing', 'paused', 'resume', 'resumes', 'resuming', 'resumed',
  'retry', 'retries', 'retrying', 'retried', 'attempt', 'attempts', 'attempting', 'attempted',
  'verify', 'verifies', 'verifying', 'verified', 'validate', 'validates', 'validating', 'validated',
  'check', 'checks', 'checking', 'checked', 'test', 'tests', 'testing', 'tested',
  'debug', 'debugs', 'debugging', 'debugged', 'trace', 'traces', 'tracing', 'traced',
  'log', 'logs', 'logging', 'logged', 'record', 'records', 'recording', 'recorded',
  'track', 'tracks', 'tracking', 'tracked', 'monitor', 'monitors', 'monitoring', 'monitored',
  'analyze', 'analyzes', 'analyzing', 'analyzed', 'analysis', 'analyses',
  'evaluate', 'evaluates', 'evaluating', 'evaluated', 'assess', 'assesses', 'assessing', 'assessed',
  'measure', 'measures', 'measuring', 'measured', 'calculate', 'calculates', 'calculating', 'calculated',
  'compute', 'computes', 'computing', 'computed', 'estimate', 'estimates', 'estimating', 'estimated',
  'compare', 'compares', 'comparing', 'compared', 'contrast', 'contrasts', 'contrasting', 'contrasted',
  'match', 'matches', 'matching', 'matched', 'equal', 'equals', 'equaling', 'equaled',
  'differ', 'differs', 'differing', 'differed', 'different', 'difference', 'differences',
  'same', 'similar', 'identical', 'equivalent', 'equal', 'equals',
  'replace', 'replaces', 'replacing', 'replaced', 'substitute', 'substitutes', 'substituting', 'substituted',
  'exchange', 'exchanges', 'exchanging', 'exchanged', 'swap', 'swaps', 'swapping', 'swapped',
  'switch', 'switches', 'switching', 'switched', 'change', 'changes', 'changing', 'changed',
  'modify', 'modifies', 'modifying', 'modified', 'alter', 'alters', 'altering', 'altered',
  'adjust', 'adjusts', 'adjusting', 'adjusted', 'adapt', 'adapts', 'adapting', 'adapted',
  'customize', 'customizes', 'customizing', 'customized', 'personalize', 'personalizes', 'personalizing', 'personalized',
  'configure', 'configures', 'configuring', 'configured', 'setup', 'setups', 'install', 'installs', 'installing', 'installed',
  'initialize', 'initializes', 'initializing', 'initialized', 'init', 'reset', 'resets', 'resetting', 'reseted',
  'reboot', 'reboots', 'rebooting', 'rebooted', 'restart', 'restarts', 'restarting', 'restarted',
  'refresh', 'refreshes', 'refreshing', 'refreshed', 'reload', 'reloads', 'reloading', 'reloaded',
  'update', 'updates', 'updating', 'updated', 'upgrade', 'upgrades', 'upgrading', 'upgraded',
  'improve', 'improves', 'improving', 'improved', 'enhance', 'enhances', 'enhancing', 'enhanced',
  'optimize', 'optimizes', 'optimizing', 'optimized', 'optimise', 'optimises', 'optimising', 'optimised',
  'refactor', 'refactors', 'refactoring', 'refactored', 'rewrite', 'rewrites', 'rewriting', 'rewrote', 'rewritten',
  'rebuild', 'rebuilds', 'rebuilding', 'rebuilt', 'recreate', 'recreates', 'recreating', 'recreated',
  'restore', 'restores', 'restoring', 'restored', 'recover', 'recovers', 'recovering', 'recovered',
  'backup', 'backups', 'backups', 'backing', 'archived', 'archive', 'archives', 'archiving',
  'store', 'stores', 'storing', 'stored', 'save', 'saves', 'saving', 'saved',
  'persist', 'persists', 'persisting', 'persisted', 'cache', 'caches', 'caching', 'cached',
  'memory', 'memories', 'storage', 'storages', 'disk', 'disks', 'drive', 'drives',
  'folder', 'folders', 'directory', 'directories', 'path', 'paths', 'location', 'locations',
  'file', 'files', 'document', 'documents', 'data', 'database', 'databases', 'record', 'records',
  'entry', 'entries', 'item', 'items', 'element', 'elements', 'object', 'objects',
  'entity', 'entities', 'model', 'models', 'schema', 'schemas', 'structure', 'structures',
  'format', 'formats', 'type', 'types', 'kind', 'kinds', 'sort', 'sorts', 'variety', 'varieties',
  'category', 'categories', 'class', 'classes', 'group', 'groups', 'set', 'sets', 'collection', 'collections',
  'list', 'lists', 'array', 'arrays', 'queue', 'queues', 'stack', 'stacks', 'heap', 'heaps',
  'tree', 'trees', 'graph', 'graphs', 'node', 'nodes', 'edge', 'edges', 'vertex', 'vertices',
  'link', 'links', 'connection', 'connections', 'reference', 'references', 'pointer', 'pointers',
  'key', 'keys', 'index', 'indices', 'indexes', 'id', 'ids', 'identifier', 'identifiers',
  'name', 'names', 'label', 'labels', 'tag', 'tags', 'title', 'titles', 'heading', 'headings',
  'header', 'headers', 'footer', 'footers', 'body', 'bodies', 'section', 'sections', 'part', 'parts',
  'segment', 'segments', 'piece', 'pieces', 'portion', 'portions', 'fraction', 'fractions',
  'whole', 'wholes', 'total', 'totals', 'sum', 'sums', 'amount', 'amounts', 'quantity', 'quantities',
  'number', 'numbers', 'count', 'counts', 'figure', 'figures', 'digit', 'digits', 'integer', 'integers',
  'decimal', 'decimals', 'fraction', 'fractions', 'percentage', 'percentages', 'ratio', 'ratios',
  'rate', 'rates', 'speed', 'speeds', 'velocity', 'velocities', 'pace', 'paces', 'frequency', 'frequencies',
  'period', 'periods', 'duration', 'durations', 'interval', 'intervals', 'span', 'spans', 'range', 'ranges',
  'scope', 'scopes', 'scale', 'scales', 'size', 'sizes', 'magnitude', 'magnitudes', 'degree', 'degrees',
  'level', 'levels', 'grade', 'grades', 'rank', 'ranks', 'rating', 'ratings', 'score', 'scores',
  'point', 'points', 'mark', 'marks', 'unit', 'units', 'measure', 'measures', 'measurement', 'measurements',
  'dimension', 'dimensions', 'aspect', 'aspects', 'factor', 'factors', 'element', 'elements',
  'component', 'components', 'constituent', 'constituents', 'ingredient', 'ingredients', 'part', 'parts',
  'piece', 'pieces', 'bit', 'bits', 'fragment', 'fragments', 'segment', 'segments', 'section', 'sections',
  'sector', 'sectors', 'division', 'divisions', 'department', 'departments', 'branch', 'branches',
  'area', 'areas', 'region', 'regions', 'zone', 'zones', 'territory', 'territories', 'domain', 'domains',
  'field', 'fields', 'sphere', 'spheres', 'realm', 'realms', 'world', 'worlds', 'universe', 'universes',
  'environment', 'environments', 'context', 'contexts', 'background', 'backgrounds', 'setting', 'settings',
  'scene', 'scenes', 'situation', 'situations', 'condition', 'conditions', 'state', 'states', 'status',
  'case', 'cases', 'instance', 'instances', 'example', 'examples', 'sample', 'samples', 'specimen',
  'model', 'models', 'pattern', 'patterns', 'template', 'templates', 'prototype', 'prototypes',
  'standard', 'standards', 'norm', 'norms', 'rule', 'rules', 'regulation', 'regulations', 'law', 'laws',
  'principle', 'principles', 'theory', 'theories', 'concept', 'concepts', 'notion', 'notions', 'idea',
  'thought', 'thoughts', 'view', 'views', 'opinion', 'opinions', 'belief', 'beliefs', 'conviction',
  'attitude', 'attitudes', 'position', 'positions', 'stance', 'stances', 'posture', 'postures',
  'approach', 'approaches', 'method', 'methods', 'methodology', 'methodologies', 'technique', 'techniques',
  'procedure', 'procedures', 'process', 'processes', 'operation', 'operations', 'action', 'actions',
  'activity', 'activities', 'task', 'tasks', 'job', 'jobs', 'work', 'works', 'assignment', 'assignments',
  'project', 'projects', 'program', 'programs', 'plan', 'plans', 'scheme', 'schemes', 'strategy',
  'policy', 'policies', 'course', 'courses', 'line', 'lines', 'way', 'ways', 'manner', 'manners',
  'mode', 'modes', 'fashion', 'fashions', 'style', 'styles', 'form', 'forms', 'shape', 'shapes',
  'structure', 'structures', 'framework', 'frameworks', 'architecture', 'architectures', 'design',
  'organization', 'organizations', 'arrangement', 'arrangements', 'order', 'orders', 'system', 'systems',
  'network', 'networks', 'web', 'webs', 'grid', 'grids', 'matrix', 'matrices', 'array', 'arrays',
  'series', 'sequence', 'sequences', 'chain', 'chains', 'string', 'strings', 'stream', 'streams',
  'flow', 'flows', 'current', 'currents', 'tide', 'tides', 'wave', 'waves', 'pulse', 'pulses',
  'rhythm', 'rhythms', 'beat', 'beats', 'tempo', 'tempos', 'pace', 'paces', 'rate', 'rates', 'speed',
  'motion', 'motions', 'movement', 'movements', 'action', 'actions', 'activity', 'activities',
  'operation', 'operations', 'function', 'functions', 'performance', 'performances', 'execution',
  'implementation', 'implementations', 'realization', 'realizations', 'achievement', 'achievements',
  'accomplishment', 'accomplishments', 'fulfillment', 'fulfillments', 'completion', 'completions',
  'success', 'successes', 'victory', 'victories', 'triumph', 'triumphs', 'win', 'wins', 'gain',
  'advantage', 'advantages', 'benefit', 'benefits', 'profit', 'profits', 'return', 'returns',
  'yield', 'yields', 'output', 'outputs', 'product', 'products', 'result', 'results', 'outcome',
  'effect', 'effects', 'consequence', 'consequences', 'impact', 'impacts', 'influence', 'influences',
  'affect', 'affects', 'implication', 'implications', 'repercussion', 'repercussions', 'sequel',
  'aftermath', 'aftermaths', 'side', 'sides', 'aspect', 'aspects', 'facet', 'facets', 'feature',
  'quality', 'qualities', 'property', 'properties', 'characteristic', 'characteristics', 'attribute',
  'trait', 'traits', 'mark', 'marks', 'sign', 'signs', 'indication', 'indications', 'symptom',
  'evidence', 'proof', 'verification', 'confirmation', 'validation', 'corroboration', 'support',
  'ground', 'grounds', 'basis', 'bases', 'foundation', 'foundations', 'base', 'bases', 'bottom',
  'root', 'roots', 'source', 'sources', 'origin', 'origins', 'beginning', 'beginnings', 'start',
  'commencement', 'inception', 'genesis', 'birth', 'creation', 'formation', 'establishment',
  'institution', 'organization', 'arrangement', 'preparation', 'development', 'growth', 'evolution',
  'progress', 'advancement', 'improvement', 'betterment', 'enhancement', 'enrichment', 'refinement',
  'polish', 'finish', 'completion', 'conclusion', 'end', 'ending', 'close', 'closure', 'termination',
  'cessation', 'stop', 'halt', 'finish', 'finale', 'finish', 'culmination', 'climax', 'peak',
  'summit', 'top', 'apex', 'pinnacle', 'zenith', 'acme', 'height', 'maximum', 'utmost', 'extreme',
  'limit', 'bounds', 'boundary', 'boundaries', 'border', 'borders', 'edge', 'edges', 'fringe',
  'periphery', 'margin', 'margins', 'rim', 'brink', 'verge', 'threshold', 'doors', 'entrance',
  'entry', 'access', 'admission', 'admittance', 'ingress', 'inlet', 'opening', 'gap', 'space',
  'room', 'place', 'spot', 'location', 'position', 'site', 'situation', 'station', 'post',
  'seat', 'center', 'middle', 'heart', 'core', 'kernel', 'nucleus', 'hub', 'focus', 'focal',
  'central', 'middle', 'mid', 'midst', 'interior', 'inside', 'inner', 'internal', 'inward',
  'within', ' enclosed', 'surrounded', 'wrapped', 'covered', 'concealed', 'hidden', 'secret',
  'private', 'personal', 'confidential', 'classified', 'restricted', 'limited', 'exclusive',
  'select', 'chosen', 'preferred', 'favorite', 'favored', 'pet', 'darling', 'beloved', 'loved',
  'liked', 'enjoyed', 'appreciated', 'valued', 'prized', 'treasured', 'cherished', 'dear',
  'precious', 'valuable', 'worthwhile', 'worthy', 'deserving', 'meritorious', 'admirable',
  'commendable', 'laudable', 'praiseworthy', 'exemplary', 'model', 'ideal', 'perfect', 'flawless',
  'impeccable', 'faultless', 'errorless', 'correct', 'accurate', 'exact', 'precise', 'strict',
  'rigorous', 'precise', 'careful', 'meticulous', 'scrupulous', 'punctilious', 'conscientious',
  'thorough', 'complete', 'comprehensive', 'exhaustive', 'full', 'entire', 'whole', 'total',
  'absolute', 'utter', 'sheer', 'complete', 'perfect', 'pure', 'unmixed', 'unadulterated',
  'straight', 'direct', 'immediate', 'instant', 'instantaneous', 'prompt', 'quick', 'rapid',
  'swift', 'speedy', 'fast', 'expeditious', 'hurried', 'hasty', 'rash', 'reckless', 'careless',
  'negligent', 'remiss', 'derelict', 'lax', 'slack', 'loose', 'relaxed', 'easy', 'lenient',
  'permissive', 'tolerant', 'indulgent', 'forbearing', 'patient', 'longsuffering', 'enduring',
  'lasting', 'durable', 'permanent', 'perpetual', 'eternal', 'everlasting', 'endless', 'infinite',
  'boundless', 'limitless', 'unlimited', 'unrestricted', 'unconstrained', 'free', 'liberated',
  'released', 'emancipated', 'independent', 'autonomous', 'sovereign', 'selfgoverning', 'free',
  'clear', 'open', 'available', 'accessible', 'obtainable', 'procurable', 'attainable', 'achievable',
  'reachable', 'approachable', 'accessible', 'friendly', 'affable', 'amiable', 'genial', 'cordial',
  'warm', 'hearty', 'sincere', 'genuine', 'authentic', 'real', 'true', 'actual', 'factual',
  'literal', 'exact', 'precise', 'accurate', 'correct', 'right', 'proper', 'appropriate',
  'suitable', 'fitting', 'fit', 'apt', 'meet', 'due', 'becoming', 'seemly', 'decorous', 'proper',
  'respectable', 'reputable', 'honorable', 'upright', 'honest', 'ethical', 'moral', 'virtuous',
  'righteous', 'good', 'benevolent', 'benign', 'kind', 'kindly', 'gracious', 'courteous', 'polite',
  'civil', 'mannerly', 'wellbred', 'refined', 'cultured', 'cultivated', 'polished', 'sophisticated',
  'worldly', 'experienced', 'practiced', 'seasoned', 'veteran', 'expert', 'master', 'adept',
  'proficient', 'skilled', 'skillful', 'accomplished', 'talented', 'gifted', 'able', 'capable',
  'competent', 'qualified', 'trained', 'prepared', 'ready', 'equipped', 'fitted', 'suited',
  'adapted', 'adjusted', 'accommodated', 'reconciled', 'harmonized', 'coordinated', 'integrated',
  'unified', 'combined', 'joined', 'connected', 'linked', 'coupled', 'paired', 'matched',
  'mated', 'married', 'wedded', 'united', 'merged', 'fused', 'blended', 'mixed', 'mingled',
  'intermingled', 'intermixed', 'combined', 'composite', 'compound', 'complex', 'complicated',
  'intricate', 'involved', 'elaborate', 'sophisticated', 'advanced', 'developed', 'mature',
  'ripe', 'ready', 'prepared', 'set', 'primed', 'conditioned', 'trained', 'drilled', 'exercised',
  'practiced', 'rehearsed', 'prepared', 'ready', 'willing', 'eager', 'keen', 'anxious', 'intent',
  'determined', 'resolved', 'decided', 'settled', 'fixed', 'established', 'determined', 'decided',
  'concluded', 'final', 'ultimate', 'eventual', 'last', 'final', 'terminal', 'concluding',
  'closing', 'finishing', 'completing', 'ending', 'terminating', 'cessation', 'discontinuance',
  'suspension', 'interruption', 'break', 'pause', 'interval', 'gap', 'space', 'opening',
  'aperture', 'hole', 'perforation', 'puncture', 'breach', 'rent', 'tear', 'split', 'fissure',
  'crack', 'crevice', 'cranny', 'chink', 'slit', 'slot', 'notch', 'nick', 'indentation',
  'dent', 'depression', 'hollow', 'cavity', 'hole', 'pit', 'crater', 'excavation', 'ditch',
  'trench', 'furrow', 'groove', 'channel', 'canal', 'conduit', 'pipe', 'tube', 'cylinder',
  'barrel', 'drum', 'cask', 'keg', 'vessel', 'container', 'receptacle', 'holder', 'carrier',
  'bearer', 'porter', 'conveyor', 'transporter', 'transmitter', 'sender', 'dispatcher',
  'shipper', 'forwarder', 'carrier', 'hauler', 'mover', 'remover', 'transferor', 'assignor',
  'grantor', 'donor', 'giver', 'bestower', 'conferrer', 'presenter', 'awarder', 'dispenser',
  'distributor', 'allocator', 'apportioner', 'divider', 'splitter', 'separator', 'sifter',
  'sorter', 'classifier', 'arranger', 'organizer', 'systematizer', 'methodizer', 'orderer',
  'regulator', 'standardizer', 'normalizer', 'regularizer', 'synchronizer', 'coordinator',
  'integrator', 'unifier', 'harmonizer', 'reconciler', 'mediator', 'intermediary', 'go-between',
  'middleman', 'broker', 'agent', 'representative', 'delegate', 'deputy', 'proxy', 'substitute',
  'replacement', 'successor', 'heir', 'inherit', 'inherits', 'inheriting', 'inherited',
  'descendant', 'descendants', 'offspring', 'progeny', 'issue', 'children', 'kids', 'young',
  'family', 'families', 'parent', 'parents', 'mother', 'mom', 'mum', 'mama', 'mommy',
  'father', 'dad', 'papa', 'daddy', 'parent', 'guardian', 'custodian', 'keeper', 'warden',
  'protector', 'defender', 'guard', 'sentry', 'sentinel', 'watchman', 'lookout', 'scout',
  'picket', 'patrol', 'patroller', 'ranger', 'warder', 'caretaker', 'janitor', 'porter',
  'concierge', 'doorman', 'gatekeeper', 'steward', 'manager', 'administrator', 'supervisor',
  'overseer', 'superintendent', 'director', 'chief', 'head', 'leader', 'boss', 'superior',
  'commander', 'captain', 'master', 'lord', 'ruler', 'governor', 'ruler', 'sovereign',
  'monarch', 'king', 'queen', 'prince', 'princess', 'duke', 'duchess', 'earl', 'count',
  'countess', 'baron', 'baroness', 'knight', 'dame', 'lady', 'lord', 'noble', 'aristocrat',
  'patrician', 'gentleman', 'lady', 'commoner', 'plebeian', 'peasant', 'serf', 'slave',
  'servant', 'helper', 'assistant', 'aide', 'aider', 'attendant', 'follower', 'disciple',
  'adherent', 'supporter', 'advocate', 'proponent', 'champion', 'defender', 'patron',
  'sponsor', 'backer', 'benefactor', 'benefactress', 'donor', 'contributor', 'subscriber',
  'member', 'affiliate', 'associate', 'partner', 'colleague', 'coworker', 'fellow', 'peer',
  'equal', 'equivalent', 'match', 'counterpart', 'parallel', 'analogue', 'correspondent',
  'complement', 'supplement', 'addition', 'accessory', 'adjunct', 'appurtenance', 'appendage',
  'attachment', 'annex', 'extension', 'wing', 'branch', 'division', 'department', 'section',
  'sector', 'segment', 'portion', 'part', 'share', 'portion', 'allotment', 'allocation',
  'quota', 'ration', 'allowance', 'stint', 'limit', 'restriction', 'constraint', 'check',
  'curb', 'control', 'restraint', 'limitation', 'bound', 'boundary', 'border', 'frontier',
  'perimeter', 'circumference', 'circuit', 'compass', 'range', 'reach', 'scope', 'extent',
  'area', 'expanse', 'stretch', 'spread', 'span', 'sweep', 'swing', 'arc', 'arch', 'curve',
  'bend', 'turn', 'twist', 'warp', 'distort', 'deform', 'transform', 'transmute', 'convert',
  'change', 'alter', 'vary', 'modify', 'adjust', 'adapt', 'accommodate', 'reconcile',
  'harmonize', 'coordinate', 'synchronize', 'integrate', 'unify', 'merge', 'fuse', 'blend',
  'mix', 'mingle', 'combine', 'compound', 'complicate', 'involve', 'entangle', 'ensnare',
  'trap', 'catch', 'capture', 'seize', 'grab', 'grasp', 'grip', 'hold', 'clasp', 'clutch',
  'cling', 'adhere', 'stick', 'attach', 'fasten', 'fix', 'secure', 'anchor', 'ground',
  'base', 'found', 'establish', 'settle', 'place', 'put', 'lay', 'set', 'position', 'situate',
  'locate', 'site', 'install', 'plant', 'park', 'deposit', 'store', 'keep', 'retain',
  'maintain', 'preserve', 'conserve', 'save', 'protect', 'guard', 'shield', 'screen',
  'shelter', 'cover', 'hide', 'conceal', 'secrete', 'cache', 'stash', 'store', 'stock',
  'supply', 'furnish', 'provide', 'afford', 'offer', 'present', 'proffer', 'tender',
  'extend', 'reach', 'stretch', 'strain', 'stress', 'emphasize', 'underline', 'underscore',
  'highlight', 'accentuate', 'accent', 'stress', 'emphasis', 'importance', 'significance',
  'consequence', 'moment', 'weight', 'gravity', 'seriousness', 'earnestness', 'solemnity',
  'formality', 'ceremony', 'ritual', 'rite', 'custom', 'tradition', 'convention', 'practice',
  'habit', 'usage', 'wont', 'routine', 'rule', 'order', 'system', 'method', 'methodology',
  'approach', 'technique', 'procedure', 'process', 'operation', 'action', 'act', 'deed',
  'feat', 'exploit', 'achievement', 'accomplishment', 'attainment', 'realization', 'fulfillment',
  'completion', 'execution', 'performance', 'enactment', 'implementation', 'application',
  'use', 'usage', 'utilization', 'employment', 'exercise', 'exertion', 'application',
  'operation', 'functioning', 'working', 'running', 'going', 'acting', 'performing',
  'playing', 'serving', 'functioning', 'operating', 'behaving', 'conducting', 'carrying',
  'bearing', 'demeanor', 'deportment', 'comportment', 'behavior', 'conduct', 'actions',
  'doings', 'activities', 'operations', 'proceedings', 'affairs', 'concerns', 'matters',
  'things', 'business', 'commerce', 'trade', 'traffic', 'dealings', 'transactions',
  'negotiations', 'bargaining', 'haggling', 'bartering', 'trading', 'exchanging',
  'swapping', 'substituting', 'replacing', 'superseding', 'supplanting', 'displacing',
  'ousting', 'ejecting', 'expelling', 'removing', 'eliminating', 'eradicating',
  'wiping', 'erasing', 'deleting', 'canceling', 'annulling', 'voiding', 'invalidating',
  'nullifying', 'negating', 'revoking', 'repealing', 'rescinding', 'countermanding',
  'overruling', 'overriding', 'vetoing', 'rejecting', 'refusing', 'declining',
  'denying', 'withholding', 'keeping', 'retaining', 'holding', 'possessing', 'owning',
  'having', 'bearing', 'containing', 'including', 'comprising', 'embracing',
  'encompassing', 'involving', 'entailing', 'implying', 'signifying', 'meaning',
  'denoting', 'indicating', 'showing', 'displaying', 'exhibiting', 'demonstrating',
  'manifesting', 'revealing', 'disclosing', 'exposing', 'uncovering', 'unveiling',
  'unmasking', 'discovering', 'finding', 'detecting', 'locating', 'spotting',
  'identifying', 'recognizing', 'knowing', 'realizing', 'understanding', 'comprehending',
  'apprehending', 'grasping', 'seizing', 'catching', 'getting', 'following', 'tracking',
  'tracing', 'pursuing', 'chasing', 'hunting', 'searching', 'seeking', 'looking',
  'hunting', 'fishing', 'prospecting', 'exploring', 'investigating', 'examining',
  'inspecting', 'checking', 'testing', 'trying', 'proving', 'verifying', 'validating',
  'confirming', 'substantiating', 'corroborating', 'supporting', 'backing', 'endorsing',
  'approving', 'sanctioning', 'authorizing', 'licensing', 'permitting', 'allowing',
  'letting', 'enabling', 'empowering', 'authorizing', 'commissioning', 'delegating',
  'deputizing', 'appointing', 'naming', 'nominating', 'designating', 'assigning',
  'allocating', 'allotting', 'apportioning', 'distributing', 'dispensing', 'dealing',
  'administering', 'managing', 'handling', 'conducting', 'directing', 'guiding',
  'leading', 'steering', 'piloting', 'navigating', 'sailing', 'cruising', 'traveling',
  'journeying', 'voyaging', 'touring', 'sightseeing', 'visiting', 'calling', 'seeing',
  'meeting', 'encountering', 'experiencing', 'undergoing', 'suffering', 'enduring',
  'bearing', 'withstanding', 'tolerating', 'abiding', 'accepting', 'receiving',
  'taking', 'getting', 'obtaining', 'gaining', 'acquiring', 'procuring', 'securing',
  'winning', 'earning', 'deserving', 'meriting', 'warranting', 'justifying', 'validating',
  'verifying', 'proving', 'confirming', 'establishing', 'demonstrating', 'showing',
  'indicating', 'suggesting', 'implying', 'inferring', 'deducing', 'concluding',
  'reasoning', 'thinking', 'believing', 'supposing', 'assuming', 'presuming',
  'expecting', 'anticipating', 'awaiting', 'waiting', 'staying', 'remaining',
  'lingering', 'delaying', 'postponing', 'deferring', 'suspending', 'staying',
  'pausing', 'stopping', 'ceasing', 'halting', 'discontinuing', 'terminating',
  'ending', 'finishing', 'completing', 'closing', 'concluding', 'finalizing',
  'settling', 'resolving', 'solving', 'answering', 'replying', 'responding',
  'reacting', 'acting', 'behaving', 'performing', 'functioning', 'operating',
  'working', 'serving', 'acting', 'playing', 'doing', 'making', 'creating',
  'producing', 'generating', 'forming', 'shaping', 'molding', 'casting',
  'forging', 'fabricating', 'manufacturing', 'constructing', 'building',
  'erecting', 'raising', 'lifting', 'elevating', 'hoisting', 'heaving',
  'boosting', 'increasing', 'augmenting', 'enhancing', 'intensifying',
  'strengthening', 'fortifying', 'reinforcing', 'supporting', 'bracing',
  'buttressing', 'shoring', 'propping', 'sustaining', 'maintaining', 'upholding',
  'preserving', 'conserving', 'keeping', 'saving', 'guarding', 'protecting',
  'defending', 'shielding', 'screening', 'sheltering', 'covering', 'hiding',
  'concealing', 'masking', 'cloaking', 'veiling', 'shrouding', 'wrapping',
  'swathing', 'bundling', 'packing', 'packaging', 'boxing', 'crating',
  'containing', 'holding', 'bearing', 'carrying', 'transporting', 'conveying',
  'transmitting', 'transferring', 'moving', 'shifting', 'transferring',
  'relocating', 'resetting', 'removing', 'taking', 'carrying', 'bringing',
  'fetching', 'getting', 'obtaining', 'gaining', 'winning', 'earning',
  'deserving', 'meriting', 'warranting', 'entitling', 'qualifying', 'fitting',
  'suiting', 'adapting', 'adjusting', 'accommodating', 'reconciling',
  'harmonizing', 'coordinating', 'synchronizing', 'integrating', 'unifying',
  'combining', 'joining', 'linking', 'connecting', 'coupling', 'pairing',
  'matching', 'mating', 'marrying', 'wedding', 'uniting', 'merging',
  'fusing', 'blending', 'mixing', 'mingling', 'intermingling', 'associating',
  'relating', 'connecting', 'linking', 'tying', 'binding', 'fastening',
  'attaching', 'affixing', 'appending', 'adding', 'tagging', 'tacking',
  'slipping', 'sneaking', 'smuggling', 'importing', 'introducing', 'inserting',
  'injecting', 'infusing', 'instilling', 'inculcating', 'implanting',
  'embedding', 'burying', 'hiding', 'concealing', 'secreting', 'masking',
  'cloaking', 'disguising', 'camouflaging', 'veiling', 'shrouding', 'clouding',
  'obscuring', 'darkening', 'dimming', 'shadowing', 'shading', 'sheltering',
  'protecting', 'guarding', 'defending', 'shielding', 'screening', 'covering',
  'roofing', 'topping', 'capping', 'crowning', 'cresting', 'peaking',
  'summiting', 'maximizing', 'optimizing', 'perfecting', 'completing',
  'finishing', 'polishing', 'refining', 'honing', 'sharpening', 'edging',
  'pointing', 'tipping', 'capping', 'crowning', 'completing', 'concluding',
  'ending', 'terminating', 'closing', 'stopping', 'ceasing', 'halting',
  'pausing', 'breaking', 'interrupting', 'suspending', 'delaying', 'postponing',
  'deferring', 'putting', 'shelving', 'tabling', 'pigeonholing', 'filing',
  'recording', 'registering', 'enrolling', 'entering', 'inputting', 'typing',
  'keying', 'writing', 'inscribing', 'engraving', 'etching', 'carving',
  'chiseling', 'sculpting', 'sculpturing', 'modeling', 'molding', 'casting',
  'founding', 'smelting', 'refining', 'purifying', 'distilling', 'extracting',
  'deriving', 'obtaining', 'getting', 'gaining', 'winning', 'earning',
  'learning', 'studying', 'reading', 'perusing', 'scanning', 'skimming',
  'browsing', 'surveying', 'reviewing', 'examining', 'inspecting', 'checking',
  'testing', 'proving', 'verifying', 'validating', 'confirming', 'ensuring',
  'assuring', 'insuring', 'guaranteeing', 'warranting', 'securing', 'safeguarding',
  'protecting', 'preserving', 'conserving', 'saving', 'keeping', 'retaining',
  'holding', 'maintaining', 'sustaining', 'supporting', 'bearing', 'carrying',
  'shouldering', 'bearing', 'enduring', 'tolerating', 'standing', 'abiding',
  'accepting', 'taking', 'receiving', 'getting', 'obtaining', 'gaining',
  'winning', 'earning', 'meriting', 'deserving', 'warranting', 'justifying',
  'excusing', 'pardoning', 'forgiving', 'overlooking', 'ignoring', 'neglecting',
  'disregarding', 'omitting', 'skipping', 'missing', 'losing', 'failing',
  'falling', 'dropping', 'sinking', 'declining', 'decreasing', 'lessening',
  'diminishing', 'reducing', 'lowering', 'cutting', 'slashing', 'trimming',
  'paring', 'pruning', 'cropping', 'shearing', 'clipping', 'snipping',
  'nipping', 'cutting', 'slicing', 'dicing', 'chopping', 'mincing',
  'grinding', 'crushing', 'smashing', 'shattering', 'breaking', 'cracking',
  'splitting', 'dividing', 'separating', 'parting', 'detaching', 'disconnecting',
  'disjoining', 'disuniting', 'alienating', 'estranging', 'divorcing',
  'separating', 'severing', 'cutting', 'slicing', 'slitting', 'splitting',
  'rending', 'tearing', 'ripping', 'rupturing', 'bursting', 'breaking',
  'fracturing', 'shattering', 'smashing', 'crushing', 'grinding', 'pounding',
  'beating', 'hitting', 'striking', 'knocking', 'tapping', 'rapping',
  'patting', 'touching', 'feeling', 'handling', 'manipulating', 'operating',
  'working', 'running', 'driving', 'steering', 'piloting', 'navigating',
  'guiding', 'directing', 'leading', 'heading', 'commanding', 'controlling',
  'managing', 'supervising', 'overseeing', 'monitoring', 'watching',
  'observing', 'viewing', 'seeing', 'looking', 'regarding', 'noticing',
  'noting', 'marking', 'perceiving', 'discerning', 'detecting', 'discovering',
  'finding', 'locating', 'spotting', 'identifying', 'recognizing', 'knowing',
  'realizing', 'understanding', 'comprehending', 'apprehending', 'grasping',
  'seizing', 'catching', 'getting', 'following', 'tracking', 'trailing',
  'shadowing', 'dogging', 'pursuing', 'chasing', 'hunting', 'searching',
  'seeking', 'questing', 'requesting', 'asking', 'inquiring', 'querying',
  'questioning', 'interrogating', 'examining', 'investigating', 'exploring',
  'probing', 'delving', 'digging', 'mining', 'excavating', 'unearthing',
  'uncovering', 'disclosing', 'revealing', 'exposing', 'unmasking',
  'discovering', 'finding', 'locating', 'pinpointing', 'identifying',
  'diagnosing', 'recognizing', 'distinguishing', 'differentiating',
  'discriminating', 'discerning', 'perceiving', 'noticing', 'noting',
  'observing', 'seeing', 'beholding', 'witnessing', 'viewing', 'watching',
  'eyeing', 'gazing', 'staring', 'looking', 'peering', 'peeking', 'peeping',
  'glancing', 'scanning', 'surveying', 'contemplating', 'regarding',
  'considering', 'pondering', 'reflecting', 'thinking', 'cogitating',
  'deliberating', 'meditating', 'musing', 'ruminating', 'wondering',
  'marveling', 'admiring', 'appreciating', 'valuing', 'esteeming',
  'regarding', 'respecting', 'honoring', 'revering', 'venerating',
  'worshiping', 'adoring', 'loving', 'liking', 'enjoying', 'preferring',
  'favoring', 'fancying', 'wanting', 'desiring', 'wishing', 'hoping',
  'expecting', 'awaiting', 'anticipating', 'looking', 'watching',
  'waiting', 'staying', 'remaining', 'lingering', 'tarrying', 'delaying',
  'postponing', 'deferring', 'suspending', 'staying', 'pausing',
  'stopping', 'halting', 'ceasing', 'desisting', 'refraining', 'forbearing',
  'abstaining', 'avoiding', 'shunning', 'eschewing', 'forsaking',
  'abandoning', 'deserting', 'leaving', 'quitting', 'exiting', 'departing',
  'going', 'moving', 'traveling', 'journeying', 'voyaging', 'touring',
  'visiting', 'calling', 'seeing', 'meeting', 'encountering', 'facing',
  'confronting', 'opposing', 'resisting', 'withstanding', 'defying',
  'challenging', 'daring', 'braving', 'venturing', 'risking', 'hazarding',
  'waging', 'betting', 'staking', 'pledging', 'promising', 'vowing',
  'swearing', 'pledging', 'committing', 'engaging', 'undertaking',
  'taking', 'assuming', 'accepting', 'receiving', 'adopting', 'embracing',
  'espousing', 'supporting', 'upholding', 'maintaining', 'sustaining',
  'continuing', 'persisting', 'persevering', 'enduring', 'lasting',
  'remaining', 'staying', 'abiding', 'dwelling', 'residing', 'living',
  'inhabiting', 'occupying', 'possessing', 'owning', 'having', 'holding',
  'bearing', 'carrying', 'wearing', 'sporting', 'displaying', 'showing',
  'exhibiting', 'manifesting', 'demonstrating', 'expressing', 'voicing',
  'uttering', 'articulating', 'enunciating', 'pronouncing', 'saying',
  'speaking', 'talking', 'telling', 'stating', 'declaring', 'announcing',
  'proclaiming', 'publishing', 'broadcasting', 'airing', 'transmitting',
  'sending', 'issuing', 'dispensing', 'distributing', 'circulating',
  'diffusing', 'disseminating', 'spreading', 'scattering', 'strewing',
  'sprinkling', 'dusting', 'powdering', 'spraying', 'splashing',
  'spattering', 'showering', 'drenching', 'soaking', 'saturating',
  'steeping', 'imbuing', 'infusing', 'instilling', 'inculcating',
  'implanting', 'embedding', 'burying', 'hiding', 'concealing', 'masking',
  'cloaking', 'veiling', 'shrouding', 'wrapping', 'enveloping', 'covering',
  'overlaying', 'spreading', 'coating', 'painting', 'varnishing',
  'lacquering', 'glazing', 'polishing', 'buffing', 'burnishing', 'rubbing',
  'scraping', 'scratching', 'scraping', 'grating', 'grinding', 'whetting',
  'honing', 'sharpening', 'pointing', 'tipping', 'capping', 'crowning',
  'completing', 'finishing', 'perfecting', 'refining', 'polishing',
  'burnishing', 'embellishing', 'decorating', 'adorning', 'ornamenting',
  'beautifying', 'enhancing', 'enriching', 'improving', 'ameliorating',
  'bettering', 'upgrading', 'refining', 'perfecting', 'completing',
  'consummating', 'accomplishing', 'achieving', 'attaining', 'realizing',
  'fulfilling', 'satisfying', 'meeting', 'filling', 'sating', 'satiating',
  'surfeiting', 'cloying', 'sickening', 'nauseating', 'disgusting',
  'revolting', 'repelling', 'repulsing', 'offending', 'affronting',
  'insulting', 'abusing', 'maltreating', 'mistreating', 'ill-treating',
  'misusing', 'misemploying', 'perverting', 'corrupting', 'debasing',
  'degrading', 'demeaning', 'humiliating', 'mortifying', 'shaming',
  'embarrassing', 'abashing', 'discomfiting', 'disconcerting', 'rattling',
  'fazing', 'disturbing', 'perturbing', 'upsetting', 'agitating',
  'flustering', 'flurrying', 'ruffling', 'shaking', 'rocking', 'jarring',
  'jolting', 'jerking', 'twitching', 'trembling', 'shivering', 'shuddering',
  'quivering', 'quavering', 'shaking', 'vibrating', 'oscillating',
  'swinging', 'swaying', 'rocking', 'rolling', 'pitching', 'yawing',
  'lurching', 'reeling', 'staggering', 'tottering', 'teetering',
  'wobbling', 'wabbling', 'wagging', 'waving', 'brandishing', 'flourishing',
  'swinging', 'twirling', 'whirling', 'spinning', 'rotating', 'revolving',
  'turning', 'circling', 'orbiting', 'circulating', 'flowing', 'streaming',
  'pouring', 'gushing', 'spouting', 'spurting', 'jetting', 'shooting',
  'springing', 'leaping', 'jumping', 'bounding', 'vaulting', 'hurdling',
  'clearing', 'surmounting', 'overcoming', 'conquering', 'defeating',
  'vanquishing', 'overthrowing', 'overwhelming', 'overpowering',
  'overcoming', 'subduing', 'suppressing', 'repressing', 'oppressing',
  'compressing', 'squeezing', 'pressing', 'squashing', 'crushing',
  'smashing', 'shattering', 'fragmenting', 'splintering', 'shivering',
  'crumbling', 'disintegrating', 'pulverizing', 'powdering', 'grinding',
  'milling', 'crushing', 'trampling', 'treading', 'stepping', 'walking',
  'marching', 'parading', 'strutting', 'swaggering', 'stalking', 'striding',
  'strolling', 'sauntering', 'ambling', 'wandering', 'rambling', 'roaming',
  'roving', 'ranging', 'drifting', 'floating', 'sailing', 'gliding',
  'sliding', 'slipping', 'skidding', 'slinking', 'sneaking', 'creeping',
  'crawling', 'climbing', 'scaling', 'mounting', 'ascending', 'rising',
  'lifting', 'raising', 'elevating', 'hoisting', 'heaving', 'boosting',
  'increasing', 'augmenting', 'enhancing', 'intensifying', 'strengthening',
  'fortifying', 'reinforcing', 'supporting', 'bracing', 'buttressing',
  'shoring', 'propping', 'sustaining', 'maintaining', 'upholding',
  'bearing', 'carrying', 'shouldering', 'tolerating', 'enduring',
  'suffering', 'undergoing', 'experiencing', 'knowing', 'realizing',
  'recognizing', 'seeing', 'witnessing', 'beholding', 'perceiving',
  'observing', 'noticing', 'noting', 'marking', 'minding', 'attending',
  'heeding', 'listening', 'hearing', 'harking', 'harkening', 'harking',
  'listening', 'giving', 'paying', 'lending', 'loaning', 'borrowing',
  'taking', 'getting', 'receiving', 'accepting', 'admitting', 'allowing',
  'letting', 'permitting', 'suffering', 'tolerating', 'bearing', 'standing',
  'abiding', 'stomaching', 'digesting', 'swallowing', 'consuming',
  'eating', 'drinking', 'imbibing', 'absorbing', 'soaking', 'sucking',
  'sopping', 'saturating', 'impregnating', 'infusing', 'instilling',
  'inculcating', 'implanting', 'embedding', 'inserting', 'introducing',
  'importing', 'bringing', 'carrying', 'bearing', 'conveying', 'transporting',
  'transmitting', 'transferring', 'moving', 'shifting', 'transferring',
  'relocating', 'resetting', 'removing', 'displacing', 'replacing',
  'substituting', 'exchanging', 'swapping', 'trading', 'bartering',
  'dealing', 'transacting', 'negotiating', 'bargaining', 'haggling',
  'dickering', 'wrangling', 'squabbling', 'quarreling', 'arguing',
  'disputing', 'debating', 'discussing', 'deliberating', 'considering',
  'pondering', 'reflecting', 'thinking', 'cogitating', 'ruminating',
  'meditating', 'contemplating', 'studying', 'examining', 'investigating',
  'exploring', 'researching', 'inquiring', 'querying', 'questioning',
  'interrogating', 'asking', 'requesting', 'soliciting', 'seeking',
  'petitioning', 'applying', 'appealing', 'pleading', 'begging',
  'imploring', 'entreating', 'beseeching', 'supplicating', 'praying',
  'invoking', 'calling', 'summoning', 'conjuring', 'invoking', 'evoking',
  'provoking', 'inciting', 'instigating', 'fomenting', 'stirring',
  'agitating', 'rousing', 'waking', 'awakening', 'wakening', 'waking',
  'rousing', 'stirring', 'moving', 'touching', 'affecting', 'impressing',
  'influencing', 'swaying', 'bending', 'turning', 'changing', 'altering',
  'varying', 'modifying', 'adjusting', 'adapting', 'accommodating',
  'reconciling', 'harmonizing', 'coordinating', 'synchronizing',
  'integrating', 'unifying', 'combining', 'joining', 'linking',
  'connecting', 'associating', 'relating', 'correlating', 'coordinating',
  'organizing', 'systematizing', 'methodizing', 'ordering', 'arranging',
  'disposing', 'positioning', 'placing', 'locating', 'situating',
  'establishing', 'instituting', 'founding', 'creating', 'making',
  'producing', 'generating', 'forming', 'shaping', 'molding', 'casting',
  'forging', 'fabricating', 'manufacturing', 'constructing', 'building',
  'erecting', 'raising', 'lifting', 'elevating', 'hoisting', 'heaving',
  'hiking', 'upping', 'raising', 'lifting', 'boosting', 'increasing',
  'augmenting', 'enhancing', 'intensifying', 'strengthening', 'fortifying',
  'reinforcing', 'supporting', 'bracing', 'buttressing', 'shoring',
  'underpinning', 'founding', 'establishing', 'grounding', 'basing',
  'rooting', 'embedding', 'fixing', 'setting', 'settling', 'planting',
  'installing', 'placing', 'putting', 'laying', 'setting', 'situating',
  'locating', 'positioning', 'stationing', 'posting', 'installing',
  'instating', 'inducting', 'initiating', 'introducing', 'launching',
  'starting', 'beginning', 'commencing', 'opening', 'originating',
  'inaugurating', 'instituting', 'establishing', 'founding', 'creating',
  'constituting', 'organizing', 'forming', 'making', 'building',
  'constructing', 'assembling', 'putting', 'erecting', 'raising',
  'rearing', 'lifting', 'elevating', 'hoisting', 'heaving', 'hiking',
  'upping', 'mounting', 'ascending', 'climbing', 'scaling', 'surmounting',
  'overcoming', 'conquering', 'besting', 'surpassing', 'exceeding',
  'transcending', 'outdoing', 'outstripping', 'outpacing', 'outrunning',
  'outdistancing', 'passing', 'surpassing', 'excelling', 'bettering',
  'improving', 'ameliorating', 'upgrading', 'refining', 'perfecting',
  'polishing', 'honing', 'sharpening', 'whetting', 'stimulating',
  'exciting', 'arousing', 'awakening', 'wakening', 'rousing', 'stirring',
  'galvanizing', 'electrifying', 'thrilling', 'exhilarating', 'delighting',
  'pleasing', 'gratifying', 'satisfying', 'contenting', 'fulfilling',
  'completing', 'consummating', 'perfecting', 'finishing', 'ending',
  'concluding', 'terminating', 'closing', 'stopping', 'ceasing',
  'desisting', 'pausing', 'breaking', 'interrupting', 'suspending',
  'postponing', 'deferring', 'delaying', 'stalling', 'detaining',
  'retaining', 'keeping', 'holding', 'maintaining', 'preserving',
  'conserving', 'saving', 'storing', 'warehousing', 'housing',
  'sheltering', 'lodging', 'accommodating', 'quartering', 'boarding',
  'billeting', 'hosting', 'entertaining', 'receiving', 'welcoming',
  'greeting', 'saluting', 'hailing', 'accosting', 'addressing',
  'approaching', 'drawing', 'nearing', 'coming', 'advancing',
  'progressing', 'proceeding', 'continuing', 'persisting', 'persevering',
  'enduring', 'lasting', 'abiding', 'remaining', 'staying', 'tarrying',
  'lingering', 'waiting', 'awaiting', 'expecting', 'anticipating',
  'looking', 'watching', 'observing', 'regarding', 'noticing', 'noting',
  'marking', 'minding', 'attending', 'heeding', 'listening', 'hearing',
  'harking', 'harkening', 'listening', 'giving', 'paying', 'according',
  'granting', 'accord', 'accords', 'accorded',
  'agree', 'agrees', 'agreeing', 'agreed', 'agreement', 'agreements',
  'accept', 'accepts', 'accepting', 'accepted', 'acceptance',
  'refuse', 'refuses', 'refusing', 'refused', 'refusal', 'refusals',
  'reject', 'rejects', 'rejecting', 'rejected', 'rejection', 'rejections',
  'decline', 'declines', 'declining', 'declined',
  'deny', 'denies', 'denying', 'denied', 'denial', 'denials',
  'object', 'objects', 'objecting', 'objected', 'objection', 'objections',
  'oppose', 'opposes', 'opposing', 'opposed', 'opposition',
  'support', 'supports', 'supporting', 'supported', 'supporter', 'supporters',
  'approve', 'approves', 'approving', 'approved', 'approval',
  'disapprove', 'disapproves', 'disapproving', 'disapproved', 'disapproval',
  'praise', 'praises', 'praising', 'praised',
  'criticize', 'criticizes', 'criticizing', 'criticized', 'criticism',
  'blame', 'blames', 'blaming', 'blamed',
  'compliment', 'compliments', 'complimenting', 'complimented',
  'flatter', 'flatters', 'flattering', 'flattered',
  'encourage', 'encourages', 'encouraging', 'encouraged', 'encouragement',
  'discourage', 'discourages', 'discouraging', 'discouraged',
  'motivate', 'motivates', 'motivating', 'motivated', 'motivation',
  'inspire', 'inspires', 'inspiring', 'inspired', 'inspiration',
  'discourage', 'discourages', 'discouraging', 'discouraged',
  'prevent', 'prevents', 'preventing', 'prevented', 'prevention',
  'allow', 'allows', 'allowing', 'allowed',
  'enable', 'enables', 'enabling', 'enabled',
  'disable', 'disables', 'disabling', 'disabled',
  'permit', 'permits', 'permitting', 'permitted', 'permission',
  'forbid', 'forbids', 'forbidding', 'forbidden',
  'require', 'requires', 'requiring', 'required', 'requirement', 'requirements',
  'demand', 'demands', 'demanding', 'demanded',
  'request', 'requests', 'requesting', 'requested',
  'suggest', 'suggests', 'suggesting', 'suggested', 'suggestion', 'suggestions',
  'recommend', 'recommends', 'recommending', 'recommended', 'recommendation', 'recommendations',
  'advise', 'advises', 'advising', 'advised', 'advice',
  'warn', 'warns', 'warning', 'warned',
  'remind', 'reminds', 'reminding', 'reminded',
  'inform', 'informs', 'informing', 'informed', 'information',
  'notify', 'notifies', 'notifying', 'notified', 'notification', 'notifications',
  'announce', 'announces', 'announcing', 'announced', 'announcement', 'announcements',
  'publish', 'publishes', 'publishing', 'published', 'publication', 'publications',
  'broadcast', 'broadcasts', 'broadcasting',
  'report', 'reports', 'reporting', 'reported',
  'describe', 'describes', 'describing', 'described', 'description', 'descriptions',
  'explain', 'explains', 'explaining', 'explained', 'explanation', 'explanations',
  'define', 'defines', 'defining', 'defined', 'definition', 'definitions',
  'clarify', 'clarifies', 'clarifying', 'clarified', 'clarification',
  'illustrate', 'illustrates', 'illustrating', 'illustrated', 'illustration',
  'demonstrate', 'demonstrates', 'demonstrating', 'demonstrated', 'demonstration',
  'prove', 'proves', 'proving', 'proved', 'proven',
  'confirm', 'confirms', 'confirming', 'confirmed', 'confirmation',
  'verify', 'verifies', 'verifying', 'verified', 'verification',
  'validate', 'validates', 'validating', 'validated', 'validation',
  'assure', 'assures', 'assuring', 'assured',
  'guarantee', 'guarantees', 'guaranteeing', 'guaranteed',
  'ensure', 'ensures', 'ensuring', 'ensured',
  'insure', 'insures', 'insuring', 'insured',
  'promise', 'promises', 'promising', 'promised',
  'commit', 'commits', 'committing', 'committed', 'commitment', 'commitments',
  'pledge', 'pledges', 'pledging', 'pledged',
  'swear', 'swears', 'swearing', 'swore', 'sworn',
  'vow', 'vows', 'vowing', 'vowed',
  'threaten', 'threatens', 'threatening', 'threatened',
  'warn', 'warns', 'warning', 'warned',
  'pretend', 'pretends', 'pretending', 'pretended',
  'claim', 'claims', 'claiming', 'claimed',
  'boast', 'boasts', 'boasting', 'boasted',
  'complain', 'complains', 'complaining', 'complained',
  'apologize', 'apologizes', 'apologizing', 'apologized', 'apology', 'apologies',
  'forgive', 'forgives', 'forgiving', 'forgave', 'forgiven',
  'thank', 'thanks', 'thanking', 'thanked',
  'congratulate', 'congratulates', 'congratulating', 'congratulated', 'congratulation', 'congratulations',
  'celebrate', 'celebrates', 'celebrating', 'celebrated', 'celebration', 'celebrations',
  'welcome', 'welcomes', 'welcoming', 'welcomed',
  'greet', 'greets', 'greeting', 'greeted',
  'introduce', 'introduces', 'introducing', 'introduced', 'introduction', 'introductions',
  'present', 'presents', 'presenting', 'presented', 'presentation', 'presentations',
  'represent', 'represents', 'representing', 'represented', 'representation',
  'symbolize', 'symbolizes', 'symbolizing', 'symbolized',
  'signify', 'signifies', 'signifying', 'signified',
  'indicate', 'indicates', 'indicating', 'indicated', 'indication',
  'demonstrate', 'demonstrates', 'demonstrating', 'demonstrated',
  'show', 'shows', 'showing', 'showed', 'shown',
  'display', 'displays', 'displaying', 'displayed',
  'exhibit', 'exhibits', 'exhibiting', 'exhibited', 'exhibition',
  'reveal', 'reveals', 'revealing', 'revealed',
  'disclose', 'discloses', 'disclosing', 'disclosed',
  'expose', 'exposes', 'exposing', 'exposed',
  'uncover', 'uncovers', 'uncovering', 'uncovered',
  'unveil', 'unveils', 'unveiling', 'unveiled',
  'discover', 'discovers', 'discovering', 'discovered', 'discovery', 'discoveries',
  'find', 'finds', 'finding', 'found',
  'detect', 'detects', 'detecting', 'detected', 'detection',
  'locate', 'locates', 'locating', 'located', 'location',
  'identify', 'identifies', 'identifying', 'identified', 'identification',
  'recognize', 'recognizes', 'recognizing', 'recognized', 'recognition',
  'distinguish', 'distinguishes', 'distinguishing', 'distinguished',
  'differentiate', 'differentiates', 'differentiating', 'differentiated',
  'discriminate', 'discriminates', 'discriminating', 'discriminated',
  'separate', 'separates', 'separating', 'separated', 'separation',
  'divide', 'divides', 'dividing', 'divided', 'division',
  'split', 'splits', 'splitting',
  'isolate', 'isolates', 'isolating', 'isolated', 'isolation',
  'connect', 'connects', 'connecting', 'connected', 'connection', 'connections',
  'join', 'joins', 'joining', 'joined',
  'link', 'links', 'linking', 'linked',
  'unite', 'unites', 'uniting', 'united',
  'combine', 'combines', 'combining', 'combined', 'combination', 'combinations',
  'merge', 'merges', 'merging', 'merged',
  'integrate', 'integrates', 'integrating', 'integrated', 'integration',
  'mix', 'mixes', 'mixing', 'mixed', 'mixture',
  'blend', 'blends', 'blending', 'blended',
  'fuse', 'fuses', 'fusing', 'fused',
  'synthesize', 'synthesizes', 'synthesizing', 'synthesized', 'synthesis',
  'compose', 'composes', 'composing', 'composed', 'composition',
  'constitute', 'constitutes', 'constituting', 'constituted',
  'form', 'forms', 'forming', 'formed', 'formation',
  'make', 'makes', 'making', 'made',
  'create', 'creates', 'creating', 'created', 'creation',
  'produce', 'produces', 'producing', 'produced', 'production',
  'generate', 'generates', 'generating', 'generated', 'generation',
  'develop', 'develops', 'developing', 'developed', 'development',
  'build', 'builds', 'building', 'built',
  'construct', 'constructs', 'constructing', 'constructed', 'construction',
  'assemble', 'assembles', 'assembling', 'assembled', 'assembly',
  'fabricate', 'fabricates', 'fabricating', 'fabricated',
  'manufacture', 'manufactures', 'manufacturing', 'manufactured',
  'forge', 'forges', 'forging', 'forged',
  'cast', 'casts', 'casting',
  'mold', 'molds', 'molding', 'molded',
  'shape', 'shapes', 'shaping', 'shaped',
  'model', 'models', 'modeling', 'modeled',
  'design', 'designs', 'designing', 'designed',
  'plan', 'plans', 'planning', 'planned',
  'scheme', 'schemes', 'scheming', 'schemed',
  'devise', 'devises', 'devising', 'devised',
  'conceive', 'conceives', 'conceiving', 'conceived',
  'invent', 'invents', 'inventing', 'invented', 'invention', 'inventions',
  'originate', 'originates', 'originating', 'originated', 'origin',
  'initiate', 'initiates', 'initiating', 'initiated', 'initiative',
  'launch', 'launches', 'launching', 'launched',
  'establish', 'establishes', 'establishing', 'established',
  'found', 'founds', 'founding', 'founded',
  'institute', 'institutes', 'instituting', 'instituted',
  'organize', 'organizes', 'organizing', 'organized', 'organization',
  'arrange', 'arranges', 'arranging', 'arranged', 'arrangement', 'arrangements',
  'order', 'orders', 'ordering', 'ordered',
  'structure', 'structures', 'structuring', 'structured',
  'systematize', 'systematizes', 'systematizing', 'systematized',
  'standardize', 'standardizes', 'standardizing', 'standardized',
  'normalize', 'normalizes', 'normalizing', 'normalized',
  'regulate', 'regulates', 'regulating', 'regulated', 'regulation',
  'control', 'controls', 'controlling', 'controlled',
  'manage', 'manages', 'managing', 'managed', 'management',
  'direct', 'directs', 'directing', 'directed', 'direction',
  'lead', 'leads', 'leading', 'led',
  'guide', 'guides', 'guiding', 'guided',
  'steer', 'steers', 'steering', 'steered',
  'pilot', 'pilots', 'piloting', 'piloted',
  'navigate', 'navigates', 'navigating', 'navigated', 'navigation',
  'drive', 'drives', 'driving', 'drove', 'driven',
  'ride', 'rides', 'riding', 'rode', 'ridden',
  'fly', 'flies', 'flying', 'flew', 'flown',
  'sail', 'sails', 'sailing', 'sailed',
  'cruise', 'cruises', 'cruising', 'cruised',
  'travel', 'travels', 'traveling', 'traveled', 'travel', 'travels',
  'journey', 'journeys', 'journeying', 'journeyed',
  'voyage', 'voyages', 'voyaging', 'voyaged',
  'tour', 'tours', 'touring', 'toured',
  'visit', 'visits', 'visiting', 'visited',
  'explore', 'explores', 'exploring', 'explored', 'exploration',
  'investigate', 'investigates', 'investigating', 'investigated', 'investigation',
  'research', 'researches', 'researching', 'researched', 'research',
  'study', 'studies', 'studying', 'studied',
  'learn', 'learns', 'learning', 'learned', 'learnt',
  'understand', 'understands', 'understanding', 'understood',
  'comprehend', 'comprehends', 'comprehending', 'comprehended',
  'grasp', 'grasps', 'grasping', 'grasped',
  'apprehend', 'apprehends', 'apprehending', 'apprehended',
  'perceive', 'perceives', 'perceiving', 'perceived', 'perception',
  'sense', 'senses', 'sensing', 'sensed',
  'feel', 'feels', 'feeling', 'felt',
  'experience', 'experiences', 'experiencing', 'experienced',
  'undergo', 'undergoes', 'undergoing', 'underwent', 'undergone',
  'suffer', 'suffers', 'suffering', 'suffered',
  'endure', 'endures', 'enduring', 'endured',
  'bear', 'bears', 'bearing', 'bore', 'born',
  'tolerate', 'tolerates', 'tolerating', 'tolerated', 'tolerance',
  'stand', 'stands', 'standing', 'stood',
  'abide', 'abides', 'abiding', 'abode',
  'accept', 'accepts', 'accepting', 'accepted',
  'receive', 'receives', 'receiving', 'received',
  'get', 'gets', 'getting', 'got', 'gotten',
  'obtain', 'obtains', 'obtaining', 'obtained',
  'gain', 'gains', 'gaining', 'gained',
  'acquire', 'acquires', 'acquiring', 'acquired', 'acquisition',
  'procure', 'procures', 'procuring', 'procured',
  'secure', 'secures', 'securing', 'secured',
  'win', 'wins', 'winning', 'won',
  'earn', 'earns', 'earning', 'earned',
  'deserve', 'deserves', 'deserving', 'deserved',
  'merit', 'merits', 'meriting', 'merited',
  'rate', 'rates', 'rating', 'rated',
  'rank', 'ranks', 'ranking', 'ranked',
  'grade', 'grades', 'grading', 'graded',
  'score', 'scores', 'scoring', 'scored',
  'mark', 'marks', 'marking', 'marked',
  'measure', 'measures', 'measuring', 'measured',
  'weigh', 'weighs', 'weighing', 'weighed',
  'count', 'counts', 'counting', 'counted',
  'calculate', 'calculates', 'calculating', 'calculated',
  'compute', 'computes', 'computing', 'computed',
  'estimate', 'estimates', 'estimating', 'estimated',
  'gauge', 'gauges', 'gauging', 'gauged',
  'assess', 'assesses', 'assessing', 'assessed', 'assessment',
  'evaluate', 'evaluates', 'evaluating', 'evaluated', 'evaluation',
  'appraise', 'appraises', 'appraising', 'appraised',
  'value', 'values', 'valuing', 'valued',
  'price', 'prices', 'pricing', 'priced',
  'cost', 'costs', 'costing', 'cost',
  'charge', 'charges', 'charging', 'charged',
  'bill', 'bills', 'billing', 'billed',
  'pay', 'pays', 'paying', 'paid',
  'spend', 'spends', 'spending', 'spent',
  'expend', 'expends', 'expending', 'expended',
  'disburse', 'disburses', 'disbursing', 'disbursed',
  'invest', 'invests', 'investing', 'invested', 'investment',
  'save', 'saves', 'saving', 'saved',
  'store', 'stores', 'storing', 'stored',
  'reserve', 'reserves', 'reserving', 'reserved',
  'keep', 'keeps', 'keeping', 'kept',
  'retain', 'retains', 'retaining', 'retained',
  'hold', 'holds', 'holding', 'held',
  'maintain', 'maintains', 'maintaining', 'maintained', 'maintenance',
  'preserve', 'preserves', 'preserving', 'preserved', 'preservation',
  'conserve', 'conserves', 'conserving', 'conserved', 'conservation',
  'protect', 'protects', 'protecting', 'protected', 'protection',
  'guard', 'guards', 'guarding', 'guarded',
  'shield', 'shields', 'shielding', 'shielded',
  'defend', 'defends', 'defending', 'defended', 'defense',
  'safeguard', 'safeguards', 'safeguarding', 'safeguarded',
  'secure', 'secures', 'securing', 'secured', 'security',
  'ensure', 'ensures', 'ensuring', 'ensured'
]);

// Month names and abbreviations
const MONTH_WORDS = new Set([
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
  'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'sept', 'oct', 'nov', 'dec'
]);

// Day names and abbreviations
const DAY_WORDS = new Set([
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
  'mon', 'tue', 'tues', 'wed', 'thu', 'thurs', 'fri', 'sat', 'sun'
]);

// Common abbreviations that should not be flagged
const COMMON_ABBREVIATIONS = new Set([
  // Time
  'am', 'pm', 'gmt', 'est', 'pst', 'cst', 'utc',
  // Titles
  'mr', 'mrs', 'ms', 'dr', 'prof', 'sr', 'jr',
  // Common
  'etc', 'eg', 'ie', 'vs', 'vol', 'inc', 'ltd', 'corp', 'llc',
  'ave', 'st', 'blvd', 'rd', 'dr', 'hwy',
  'apt', 'ste', 'fl', 'bldg', 'dept',
  'tel', 'fax', 'email', 'www', 'http', 'https',
  'no', 'nos', 'fig', 'figs', 'et', 'al',
  'pp', 'pg', 'pgs', 'vol', 'vols', 'ed', 'eds',
  // Technology
  'css', 'html', 'js', 'ts', 'jsx', 'tsx', 'api', 'url', 'uri', 'json', 'xml', 'yaml',
  'sql', 'db', 'ui', 'ux', 'os', 'cpu', 'gpu', 'ram', 'rom', 'ssd', 'hdd',
  'pdf', 'png', 'jpg', 'jpeg', 'gif', 'svg', 'mp3', 'mp4', 'avi', 'mov',
  'npm', 'yarn', 'git', 'github', 'gitlab', 'vscode', 'ide',
  // Business
  'kpi', 'roi', 'b2b', 'b2c', 'saas', 'paas', 'iaas', 'crm', 'erp',
  // Academic
  'phd', 'md', 'ba', 'bs', 'ma', 'ms', 'mba', 'jd'
]);

// All valid words combined
const VALID_WORDS = new Set([...COMMON_WORDS, ...MONTH_WORDS, ...DAY_WORDS, ...COMMON_ABBREVIATIONS]);

// Common misspellings mapping
const COMMON_MISSPELLINGS: Record<string, string> = {
  'teh': 'the', 'hte': 'the', 'thier': 'their', 'recieve': 'receive',
  'seperate': 'separate', 'occured': 'occurred', 'definately': 'definitely',
  'occurence': 'occurrence', 'accomodate': 'accommodate', 'acommodate': 'accommodate',
  'acheive': 'achieve', 'accross': 'across', 'adress': 'address', 'adresses': 'addresses',
  'appearence': 'appearance', 'appearences': 'appearances', 'arguement': 'argument',
  'arguements': 'arguments', 'assasination': 'assassination', 'basicly': 'basically',
  'beleive': 'believe', 'beleives': 'believes', 'beleiving': 'believing',
  'benifit': 'benefit', 'benifits': 'benefits', 'becomeing': 'becoming',
  'becuase': 'because', 'begining': 'beginning', 'beleived': 'believed',
  'calender': 'calendar', 'catagory': 'category', 'cemetary': 'cemetery',
  'changable': 'changeable', 'cheif': 'chief', 'colllect': 'collect',
  'comming': 'coming', 'commited': 'committed', 'completely': 'completely',
  'concious': 'conscious', 'copywrite': 'copyright', 'curiousity': 'curiosity',
  'decieve': 'deceive', 'definate': 'definite',
  'desireable': 'desirable', 'diarhea': 'diarrhea', 'dissapoint': 'disappoint',
  'ecstacy': 'ecstasy', 'embarass': 'embarrass', 'enviroment': 'environment',
  'equiped': 'equipped', 'existance': 'existence', 'experiance': 'experience',
  'finaly': 'finally', 'folowing': 'following', 'foriegn': 'foreign',
  'freind': 'friend', 'goverment': 'government', 'gracefull': 'graceful',
  'garantee': 'guarantee', 'happyness': 'happiness', 'harrass': 'harass',
  'heighth': 'height', 'heirarchy': 'hierarchy', 'humerous': 'humorous',
  'imediately': 'immediately', 'independant': 'independent', 'indispensible': 'indispensable',
  'innoculate': 'inoculate', 'inteligence': 'intelligence', 'intresting': 'interesting',
  'irresistable': 'irresistible', 'knowlege': 'knowledge', 'liason': 'liaison',
  'libary': 'library', 'lisence': 'license', 'maintainance': 'maintenance',
  'managment': 'management', 'millenium': 'millennium', 'miniture': 'miniature',
  'miniscule': 'minuscule', 'mispell': 'misspell', 'neccessary': 'necessary',
  'noticable': 'noticeable', 'occassion': 'occasion',
  'occurance': 'occurrence', 'ocurring': 'occurring', 'paralell': 'parallel',
  'paticular': 'particular', 'peice': 'piece', 'percieve': 'perceive',
  'perserverance': 'perseverance', 'posession': 'possession', 'prefered': 'preferred',
  'presance': 'presence', 'priviledge': 'privilege', 'publically': 'publicly',
  'recogize': 'recognize', 'recomend': 'recommend',
  'relevent': 'relevant', 'religous': 'religious', 'repetion': 'repetition',
  'restarant': 'restaurant', 'rythm': 'rhythm', 'sacreligious': 'sacrilegious',
  'sieze': 'seize', 'sillhouette': 'silhouette',
  'similiar': 'similar', 'sincerly': 'sincerely', 'speach': 'speech',
  'stratagy': 'strategy', 'sucess': 'success', 'suprise': 'surprise',
  'tommorow': 'tomorrow', 'tongue': 'tongue', 'truely': 'truly',
  'unforseen': 'unforeseen', 'unfortunatly': 'unfortunately', 'untill': 'until',
  'wierd': 'weird', 'wether': 'whether', 'wich': 'which', 'withdrawl': 'withdrawal',
  'writting': 'writing', 'yeild': 'yield',
  // OCR errors
  'leamin': 'learning', 'learnin': 'learning',
  'foundatlon': 'foundation',
  'hoope': 'hooper', 'hoopee': 'hooper',
  'foun dation': 'foundation', 'foun dations': 'foundations'
};

// Context-aware expansions for abbreviations
const ABBREVIATION_EXPANSIONS: Record<string, string> = {
  'jan': 'January', 'feb': 'February', 'mar': 'March', 'apr': 'April',
  'may': 'May', 'jun': 'June', 'jul': 'July', 'aug': 'August',
  'sep': 'September', 'sept': 'September', 'oct': 'October', 'nov': 'November', 'dec': 'December',
  'mon': 'Monday', 'tue': 'Tuesday', 'tues': 'Tuesday', 'wed': 'Wednesday',
  'thu': 'Thursday', 'thurs': 'Thursday', 'fri': 'Friday', 'sat': 'Saturday', 'sun': 'Sunday'
};

function levenshteinDistance(a: string, b: string): number {
  const matrix: number[][] = [];
  for (let i = 0; i <= b.length; i++) {
    matrix[i] = [i];
  }
  for (let j = 0; j <= a.length; j++) {
    matrix[0][j] = j;
  }
  for (let i = 1; i <= b.length; i++) {
    for (let j = 1; j <= a.length; j++) {
      if (b.charAt(i - 1) === a.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          matrix[i][j - 1] + 1,
          matrix[i - 1][j] + 1
        );
      }
    }
  }
  return matrix[b.length][a.length];
}

function findSimilarWords(word: string, maxDistance: number = 1): string[] {
  const scoredSuggestions: Array<{ word: string; score: number }> = [];
  const lowerWord = word.toLowerCase();
  
  // Don't suggest short words as corrections for longer words
  const minLength = Math.max(2, lowerWord.length - 1);
  const maxLength = lowerWord.length + 1;
  
  for (const dictWord of VALID_WORDS) {
    // Skip words that are too different in length
    if (dictWord.length < minLength || dictWord.length > maxLength) continue;
    
    // Skip very short dictionary words as suggestions for longer words
    if (dictWord.length <= 3 && lowerWord.length > 4) continue;
    
    const distance = levenshteinDistance(lowerWord, dictWord);
    if (distance <= maxDistance && distance > 0) {
      // Prioritize same-length words or words with similar length
      const lengthDiff = Math.abs(dictWord.length - lowerWord.length);
      const score = distance + (lengthDiff * 0.5);
      scoredSuggestions.push({ word: dictWord, score });
    }
  }
  
  // Sort by score (lower is better) and return top 3
  scoredSuggestions.sort((a, b) => a.score - b.score);
  return scoredSuggestions.slice(0, 3).map(s => s.word);
}

function isValidWord(word: string): boolean {
  const lowerWord = word.toLowerCase();
  
  // Check common words
  if (VALID_WORDS.has(lowerWord)) return true;
  
  // Check for numbers (dates, years, etc.)
  if (/^\d+(st|nd|rd|th)?$/.test(lowerWord)) return true;
  
  // Check for year ranges
  if (/^\d{4}$/.test(lowerWord)) return true;
  
  // Check for numbers like "202" (partial year from OCR)
  if (/^\d{3}$/.test(lowerWord)) return true;
  
  return false;
}

export class SpellEngine implements ValidationEngine {
  name = 'Spell Engine';
  version = '1.0.0';
  enabled = true;

  async analyze(document: NormalizedDocument): Promise<ValidationIssue[]> {
    const issues: ValidationIssue[] = [];
    const words = document.tokens.filter(t => t.type === 'word');

    for (const token of words) {
      const word = token.text.toLowerCase();
      const originalWord = token.text;
      
      // Skip short words (1-2 characters)
      if (word.length <= 2) continue;
      
      // Skip pure numbers
      if (/^\d+$/.test(word)) continue;
      
      // Skip valid words
      if (isValidWord(word)) continue;
      
      // Skip words that look like OCR artifacts (mixed alphanumeric that's not a known pattern)
      if (/^[a-z]+\d+[a-z]+$/.test(word) && !/^(css|html|js|ts|jsx|tsx|api|url|uri|json|xml|yaml|sql|db|ui|ux|os|cpu|gpu|ram|rom|ssd|hdd|pdf|png|jpg|jpeg|gif|svg|mp3|mp4|avi|mov|npm)$/i.test(word)) {
        // Likely an OCR error, skip it
        continue;
      }
      
      // Check for common misspellings
      if (COMMON_MISSPELLINGS[word]) {
        issues.push({
          id: generateId(),
          type: 'spell',
          severity: 'medium',
          message: `Possible misspelling: "${originalWord}"`,
          suggestions: [COMMON_MISSPELLINGS[word]],
          startIndex: token.startIndex,
          endIndex: token.endIndex,
          confidence: 0.95,
          engine: this.name,
          rule: 'common-misspelling'
        });
        continue;
      }

      // Find similar words for suggestions
      const suggestions = findSimilarWords(word);
      
      if (suggestions.length > 0) {
        // Check if this is an abbreviation that could be expanded
        if (ABBREVIATION_EXPANSIONS[word]) {
          // Don't flag as error, but suggest expansion
          issues.push({
            id: generateId(),
            type: 'grammar',
            severity: 'low',
            message: `Abbreviation: "${originalWord}"`,
            suggestions: [ABBREVIATION_EXPANSIONS[word]],
            startIndex: token.startIndex,
            endIndex: token.endIndex,
            confidence: 0.85,
            engine: this.name,
            rule: 'abbreviation-expansion'
          });
        } else {
          const confidence = Math.max(0.5, 0.85 - (suggestions.length * 0.1));
          issues.push({
            id: generateId(),
            type: 'spell',
            severity: suggestions.length === 1 && levenshteinDistance(word, suggestions[0]) === 1 ? 'medium' : 'low',
            message: `Possible misspelling: "${originalWord}"`,
            suggestions: suggestions.slice(0, 3),
            startIndex: token.startIndex,
            endIndex: token.endIndex,
            confidence,
            engine: this.name,
            rule: 'dictionary-check'
          });
        }
      }
    }

    return issues;
  }
}

export const spellEngine = new SpellEngine();
